### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by zenorocha** [dracula/textual#2]
Hey @goronfreeman or @imranismail, can you add a screenshot to the repository? I want to create a page for this project on draculatheme.com ;)

**Comment by zenorocha** [comment]
Friendly ping, any updates on this?

**Comment by imranismail** [comment]
@zenorocha Added a screenshot to README.md

**Comment by zenorocha** [comment]
Thanks @imranismail!

Just added the textual theme on https://draculatheme.com/textual https://github.com/dracula/textual/commit/7254ec7497997151a12fd9d876a6387109a55980
