### ISSUE TITLE
Dracula crashes Textual 7

### ISSUE THREAD

**Issue by flntfnd** [dracula/textual#3]
I'm unsure which specific aspect of it is making version 7 (.0.8) angry, but upon activating the theme in 7 it will inform you that it's not made to work with this version. If you activate it anyway, it will crash at random.

**Comment by deadman36g** [comment]
I am having the same exact issue

**Comment by zenorocha** [comment]
Can you take a look @imranismail?

**Comment by falzm** [comment]
It doesn't crash mine, but it prints an error message saying that it's not designed to work with this version: 

<img width="538" alt="screen shot 2018-09-26 at 11 05 23" src="https://user-images.githubusercontent.com/1122379/46069599-2e330080-c17c-11e8-940f-e959d279a89f.png">

**Comment by falzm** [comment]
It is actually simple to fix this: in the Data/Settings/styleSettings.plist style file set the `Template Engine Versions` value to `4` instead of `3`.
